#:schema node_modules/wrangler/config-schema.json

# Visit https://developers.cloudflare.com/workers/wrangler/configuration/ to see full list of options for this file

# This will be the name of your worker in the Cloudflare Dashboard
name = "react-router-cloudflare-d1"
# Compatibility date docs: https://developers.cloudflare.com/workers/configuration/compatibility-dates/
compatibility_date = "2024-11-18"
# See https://developers.cloudflare.com/workers/configuration/compatibility-flags/ for full list of flags
compatibility_flags = ["nodejs_compat"]
# Entry point for the worker app
main = "./build/server/worker.js"

[build]
command = "pnpm build"

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/ - these are the static assets served to clients
directory = "./build/client"

# These vars apply to both development & production
[vars]
VALUE_FROM_CLOUDFLARE="Edit this value from wranlger.toml"
# Values defined in .dev.vars will overwrite values here
CLOUDFLARE_ACCOUNT_ID=""
CLOUDFLARE_DATABASE_ID=""

[[d1_databases]]
binding = "DB"
database_name = "rr-cloudflare-demo"
database_id = "fc17e5e7-3203-41e5-bea7-27c45dbc4792"
migrations_dir = "drizzle"

# You can create different environments that have their own bindings/variables
# See https://developers.cloudflare.com/workers/wrangler/environments/ for more information
[env.preview]
workers_dev = true

[env.preview.vars]
VALUE_FROM_CLOUDFLARE="Edit this value from wranlger.toml (env.preview.vars)"
CLOUDFLARE_ACCOUNT_ID=""
CLOUDFLARE_DATABASE_ID=""

[[env.preview.d1_databases]]
binding = "DB"
# You can keep these values the same as the database config above if you want to use a single database
database_name = "rr-cloudflare-demo"
database_id = "fc17e5e7-3203-41e5-bea7-27c45dbc4792"
migrations_dir = "drizzle"
